[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
macroquad = "0.4.13"
num_enum = "0.7.3"
rand = "0.8.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
